#!/bin/bash

# Telegram User Bot Linking - Demo Script
# This script demonstrates the database schema and linking workflow

echo "==================================="
echo "Telegram User Bot Linking - Demo"
echo "==================================="
echo ""

echo "1. Database Schema Changes"
echo "--------------------------"
echo ""
echo "Added to 'user' table:"
echo "  - telegram_chat_id VARCHAR UNIQUE"
echo ""
echo "Created 'pending_telegram_links' table:"
echo "  - link_id (UUID)"
echo "  - user_id (reference to user)"
echo "  - telegram_chat_id"
echo "  - telegram_username"
echo "  - status (pending/approved/rejected/expired)"
echo "  - approval_code (6-digit code)"
echo "  - expires_at (24 hours from creation)"
echo ""

echo "2. Linking Workflow"
echo "-------------------"
echo ""
echo "Step 1: User initiates linking"
echo "  User: /link 081235114745"
echo "  Bot:  Creates pending link request"
echo "  Bot:  Generates approval code (e.g., 123456)"
echo "  Bot:  Saves to pending_telegram_links table"
echo ""

echo "Step 2: User approves linking"
echo "  User: /approve 123456"
echo "  Bot:  Verifies approval code"
echo "  Bot:  Updates user.telegram_chat_id = <chat_id>"
echo "  Bot:  Marks pending link as 'approved'"
echo "  Bot:  Confirms successful linking"
echo ""

echo "Step 3: User accesses menu"
echo "  User: /menu"
echo "  Bot:  Checks if user.telegram_chat_id matches"
echo "  Bot:  Displays menu if authenticated"
echo ""

echo "3. Menu Options"
echo "---------------"
echo ""
echo "1. Lihat Data Saya - View profile information"
echo "2. Update Data     - Modify profile fields"
echo "   Available fields:"
echo "   - Nama (Name)"
echo "   - Pangkat (Rank)"
echo "   - Satfung (Function)"
echo "   - Jabatan (Position)"
echo "   - Instagram"
echo "   - TikTok"
echo "   - Desa Binaan (for Ditbinmas users)"
echo "3. Keluar          - Exit menu"
echo ""

echo "4. Security Features"
echo "--------------------"
echo ""
echo "✓ One-to-one mapping (1 Telegram = 1 User)"
echo "✓ Approval required (explicit user consent)"
echo "✓ Time-limited codes (24 hour expiration)"
echo "✓ Duplicate prevention (no double linking)"
echo "✓ Authentication check (all operations require linking)"
echo ""

echo "5. SQL Migrations"
echo "-----------------"
echo ""
echo "Migration files created:"
echo "  - sql/migrations/20260203_add_telegram_chat_id_to_user.sql"
echo "  - sql/migrations/20260203_create_pending_telegram_links.sql"
echo ""
echo "Apply with:"
echo "  psql -U cicero -d cicero_db -f sql/migrations/20260203_add_telegram_chat_id_to_user.sql"
echo "  psql -U cicero -d cicero_db -f sql/migrations/20260203_create_pending_telegram_links.sql"
echo ""

echo "==================================="
echo "Demo Complete!"
echo "==================================="
